<template>
  <div>
    <div v-html="title"></div>
    <div class="wx" @click="dialogVisible = true" style="text-align: center">
      <img src="../assets/wx.jpg" alt="点击分享" title="点击分享"/>
    </div>
    <div v-html="content"></div>
    <el-dialog
        title="打开微信扫描如下二维码"
        :visible.sync="dialogVisible"
        width="30%"
        center>
      <div style="text-align: center">
        <vue-qr :text="shareData.url" :margin="10" colorDark="#000" colorLight="#fff" :dotScale="1" :logoSrc="shareData.icon" :logoScale="0.2" :size="200"></vue-qr>
      </div>
      <span slot="footer" class="dialog-footer">
        <el-button @click="dialogVisible = false">取 消</el-button>
        <el-button type="primary" @click="dialogVisible = false">确定</el-button>
      </span>
    </el-dialog>
  </div>

</template>

<script>
import share from '@/assets/js/share'
import vueQr from 'vue-qr'
export default {
  name: "wxShare",
  components: {
    vueQr
  },
  mounted() {
    const url = location.href.split('#')[0];
    console.log(url)
    const dataForWeixin = {
      title: '中共北京市委 北京市人民政府印发《关于促进中医药传承创新发展的实施方案》的通知',    // 分享标题
      desc: '为贯彻落实《中共中央、国务院关于促进中医药传承创新发展的意见》精神，结合本市实际，制定如下实施方案',            // 内容描述
      linkurl: window.location.href.toString(), // 分享链接,该链接域名或路径必须与当前页面对应的公众号JS安全域名一致
      img: 'http://wx.qlogo.cn/mmopen/ciaIftfPzwlo0coPuwwLS5Fw9UwGMlxY2ziaWpqXzevJI8dKeDvk4n3NxtZS4D8dNHSYUhbiaA6IIGnFsiagEbRlaExselicC3pEA/64',        // 分享内容显示的图片(图片必须是正方形的链接)
    };
    share.getJSSDK(url,dataForWeixin)
  },
  methods: {

  },
  data() {
    return {
      dialogVisible: false,
      shareData: {
        // url: 'http://cxyabc.vaiwan.com/to_detail',  //需要转化成二维码的网址
        url: window.location.href.toString(),  //需要转化成二维码的网址
        icon: require('@/assets/img.png')  //二维码中间的图片,可以不设置
      },
      title: '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; text-align: center; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;" align="center"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">中共北京市委 北京市人民政府印发《关于促进中医药传承创新发展的实施方案》的通知</span></strong></p>\n',
      content: '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">各区委、区政府，市委各部委办，市各国家机关，各国有企业，各人民团体，各高等院校：</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　现将《关于促进中医药传承创新发展的实施方案》印发给你们，请结合实际认真贯彻落实。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 24.0pt; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; text-align: right; line-height: 150%; margin: 7.8pt 24.0pt 7.8pt 0cm;" align="right"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">中共北京市委　</span><span style="font-family: 微软雅黑, sans-serif; font-size: 12pt;">北京市人民政府</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 24.0pt; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; text-align: right; line-height: 150%; margin: 7.8pt 24.0pt 7.8pt 0cm;" align="right"><span lang="EN-US" style="font-size: 12pt; line-height: 150%; font-family: 微软雅黑, sans-serif;">2021</span><span style="font-size: 12pt; line-height: 150%; font-family: 微软雅黑, sans-serif;">年<span lang="EN-US">3</span>月<span lang="EN-US">27</span>日</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; text-align: center; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;" align="center"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">关于促进中医药传承创新发展的实施方案</span></strong></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　为贯彻落实《中共中央、国务院关于促进中医药传承创新发展的意见》精神，结合本市实际，制定如下实施方案。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<strong style="mso-bidi-font-weight: normal;">一、总体要求</strong></span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　以习近平新时代中国特色社会主义思想为指导，深入贯彻党的十九大和十九届二中、三中、四中、五中全会精神，认真落实习近平总书记关于中医药工作的重要论述，遵循中医药发展规律，传承精华、守正创新，坚持中西医并重，推动中医药和西医药相互补充、协调发展，推动中医药事业和产业高质量发展，推动中医药走向世界。到<span lang="EN-US">2025</span>年，首都中医药卫生、经济、科技、文化、生态&ldquo;五种资源&rdquo;发展更加协调，对健康北京和首都经济社会发展的贡献度明显提升。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<strong style="mso-bidi-font-weight: normal;">二、优化中医药服务体系</strong></span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>一<span lang="EN-US">)</span>开展国家级、市级中医医学中心建设。争创国家中医医学中心和国家区域中医医疗中心，建设好市级中医医学中心。鼓励央属、市属中医医疗机构通过医疗联合体等方式在基层设立门诊部、诊所等服务延伸点，逐步实现连锁经营。建成以国家级和市级中医医学中心为龙头，各级各类中医医疗机构和其他医疗机构中医科室为骨干，基层医疗卫生机构为基础，融预防保健、疾病治疗和康复于一体的中医药服务体系，提供覆盖全人群和全生命周期的中医药服务。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>二<span lang="EN-US">)</span>加强非中医医疗机构中医药服务功能。优化提升政府举办的二级以上综合医院、妇幼保健院中医科室建设，具备条件的专科医院和社区卫生服务中心要设置中医科室并提供中药饮片服务。到<span lang="EN-US">2025</span>年，实现<span lang="EN-US">100%</span>的社区卫生服务站和<span lang="EN-US">90%</span>的村卫生室能够提供<span lang="EN-US">4</span>类以上中医药技术方法。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>三<span lang="EN-US">)</span>补齐中医药服务短板。扩大中医医疗机构老年病科服务规模，改善服务条件，鼓励中医医疗机构提供安宁疗护、临终关怀、养老护理等服务。建设中医药健康养老联合体，更好发挥中医药在养老机构中的作用，在养老护理员分级培训和照护工作中增加中医内容。建立市属中医医疗机构与儿童医院协同机制，推动具有中医药特色优势的国家儿童医学中心建设。推动开展代表性中医妇科、儿科流派名医传承品牌工作室建设。支持儿童用中成药研发。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>四<span lang="EN-US">)</span>完善中医药参与突发公共卫生事件应急工作机制。在定点医院开展重点传染病中医药证候学信息监测，完善传染病预测预警机制，实现中医药&ldquo;早参与、早用药、早治愈&rdquo;。加强中医药古籍精华的梳理和挖掘，更好发挥中医药在传染病防治和突发公共卫生事件应急处置中的作用。依托国家级和市级中西医结合传染病临床基地，开展传染病防治能力培训，加强中医药群体防治方案和防治技术在全市的推广和普及。在应对突发公共卫生事件中开展中药预防性投药等工作，发挥中医药特色优势。建立突发公共卫生事件中药战略储备目录，加强中药战略储备。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>五<span lang="EN-US">)</span>发挥中医药在康复服务中的独特作用。组织制定实施心脑血管病、糖尿病、高血压、肺系病等慢性病，肿瘤等重大疾病和肢体伤残等创伤疾病的中医药康复方案。到<span lang="EN-US">2025</span>年，<span lang="EN-US">100%</span>的社区卫生服务站和<span lang="EN-US">90%</span>的村卫生室至少完成<span lang="EN-US">1</span>名医师<span lang="EN-US">(</span>或乡村医生<span lang="EN-US">)</span>的中医康复技能培训。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>六<span lang="EN-US">)</span>高水平规划中医药京津冀协同发展。推广中医药重点专科托管创新机制，推动河北雄安新区与北京中医药合作，促进中医药医疗、教育、科研共谋共建共享发展。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<strong style="mso-bidi-font-weight: normal;">三、改善中医药服务模式</strong></span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>七<span lang="EN-US">)</span>打造中西医结合发展高地。加大对现有中西医结合医院的支持力度，丰富中西医结合内涵，提升服务水平。鼓励综合医院和中医、中西医结合医院联合建设<span lang="EN-US">10</span>至<span lang="EN-US">15</span>个中西医结合重大疑难疾病临床防治基地。实施非中医医院中医药工作提升计划，在市属医院中建立中医医院牵头、联合其他医院中医科的中医医疗联合体，健全中西医多学科诊疗常态化机制，遴选并推广<span lang="EN-US">10</span>至<span lang="EN-US">20</span>种常见病种的中医药技术方法。实施重大疑难疾病中西医协同攻关计划。到<span lang="EN-US">2025</span>年，形成并推广癌症、心脑血管病、糖尿病、感染性疾病、老年痴呆和抗生素耐药问题等<span lang="EN-US">50</span>个病种的中西医结合诊疗方案。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>八<span lang="EN-US">)</span>完善优质中医药资源下沉基层工作机制。完善区域中医医师基层定期巡诊制度。推广普及<span lang="EN-US">100</span>项基层中医医疗技术。加强社区中医药服务的监测，完善中医药工作评价体系。扩大农村订单定向免费培养中医专业医学生规模。完善退休中医医师基层服务补助标准。在全科医师和乡村医生培训中增加更多中医药知识和技能内容。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>九<span lang="EN-US">)</span>发挥中医药特色优势。实施中医药重点专科提升计划，建设好中医药服务优势明显的<span lang="EN-US">10</span>类重点专科，打造中医药临床服务优质品牌。整合现有资源，推动建设<span lang="EN-US">20</span>个中医药特色服务示范医院、<span lang="EN-US">3</span>个有中医药特点的急危重症临床基地和<span lang="EN-US">10</span>个中医内病外治临床应用基地。建立中医医疗技术分级分类目录，加强对高风险中医医疗技术事中事后监管。建设北京市中医药循证医学中心，率先在全国筛选出<span lang="EN-US">50</span>个中医治疗优势病种和<span lang="EN-US">100</span>项适宜技术、<span lang="EN-US">100</span>个疗效独特的中药品种。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>十<span lang="EN-US">)</span>升级治未病健康工程。探索建立治未病处方库，试点治未病处方制度。将适宜治未病项目纳入家庭医生签约服务包，鼓励家庭医生提供中医治未病签约服务。在本市基本公共卫生服务项目中丰富中医治未病内容，鼓励商业保险机构开发中医治未病相关保险产品。将治未病服务作为重要内容纳入健康联合体试点。推进治未病服务项目纳入医疗机构收费项目试点，确定收费标准。在重点人群和慢性病患者中推广<span lang="EN-US">20</span>个中医治未病干预方案。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>十一<span lang="EN-US">)</span>启动健康北京中医药行动。发布《首都市民中医养生保健手册》，在全民健身运动中大力普及太极拳、健身气功<span lang="EN-US">(</span>如八段锦<span lang="EN-US">)</span>等养生保健方法，将中医药系列行动覆盖全生命周期。实施中医药健康文化素养提升工程，定期开展中医药健康文化素养评价。建设中医养生保健技术和方法库，推动建立中医养生保健服务人员基于第三方的培训机制。建立与媒体的联动机制，加强对中医药健康知识宣传和信息发布的指导。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<strong style="mso-bidi-font-weight: normal;">四、推动中医药科技创新</strong></span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>十二<span lang="EN-US">)</span>推动中医药科研平台建设。探索市级中医药研究机构的建设。整合央地中医药科研机构、高等学校等科技资源，推动中医药参与&ldquo;三城一区&rdquo;、中关村科技园区等科技创新园区的建设。推动创建国家中医药重点实验室、国家中医药循证医学中心。支持企业、医疗机构、高等学校、科研机构等协同创新，建设中医药产品研发、成果转化和应用示范平台，以产业链、服务链布局创新链，完善中医药产学研一体化创新模式。着力推动中西医高等学校、科研机构、医疗机构强强联合、汇聚创新。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>十三<span lang="EN-US">)</span>完善中医药创新保障机制。梳理中医药重大科学问题和工程技术难题，建立以产业目标为导向的科学问题库。发布中医药科技规划，中医药创新研究项目按科研项目管理方式给予支持。建立名老中医经验方开发保护机制，落实中医药法关于建设中医药传统知识保护名录和数据库的要求，探索建立中医药知识产权保护评估机制。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>十四<span lang="EN-US">)</span>落实&ldquo;互联网<span lang="EN-US">+</span>中医药健康服务&rdquo;行动。依托北京市卫生健康信息平台以及信息基础设施和公共数据资源，加强对中医药特色健康服务的信息化管理，实现中医药服务信息数据开放共享。逐步提高中医医疗机构电子病历分级评价和互联互通成熟度测评等级。支持中医医疗机构开展互联网服务，应用前瞻性技术开发中医智能辅助诊疗系统，推动开展线上线下一体化服务和远程医疗服务。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>十五<span lang="EN-US">)</span>推进中医药标准化建设。进一步整合资源，加快中医药标准化人才培养，建立中医药标准研究、制定、推广和监测体系。围绕中医、中药材、中药产品、中医药医疗器械设备等方面，制定和推广一批相关标准。加快建立中医药综合统计制度。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>十六<span lang="EN-US">)</span>加强中医药综合监管信息化。依托北京市卫生健康监管信息系统，加强中医药综合监管信息的汇集、分析、研判，建立部门信息共享机制。完善中医医疗机构综合监督制度，健全中医药质量控制体系，建立健全中医药质量抽检抽查制度，会同相关部门建立违法失信联合惩戒制度。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<strong style="mso-bidi-font-weight: normal;">五、推进中医药文化传播</strong></span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>十七<span lang="EN-US">)</span>启动中医药文化&ldquo;钥匙&rdquo;工程。统筹各级各类社科研究机构等建立中医药文化研究中心，研究阐释中医药的中华传统文化基因以及与其他中华优秀文化的内在联系。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>十八<span lang="EN-US">)</span>推进中医药文化遗产的保护。开展北京中医药文化资源普查。稳步推进中医药文物、老字号、名医故居等的保护利用工作，组织申报相应级别文物保护单位和认定不可移动文物。积极推动实施国家和本市非物质文化遗产中医药项目的申报和保护、展示、传承、振兴计划。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>十九<span lang="EN-US">)</span>推进中医药文化推广普及。借助现代数字传媒、动漫演艺等方式传播中医药文化。在中小学开展中医药文化&ldquo;六个一&rdquo;<span lang="EN-US">(</span>一经、一书、一园、一操、一网、一班<span lang="EN-US">)</span>行动。探索在高等学校开设中医药选修课程，支持在高等学校建立中医药社团，在老年大学开设适合老年人特点的中医药课程，在社区课堂、市民学校等社区教育培训活动中开展中医药健康知识讲座。推进中医药传统文化进机关、企业、社区、农村、家庭，支持社会力量举办的中医药博物馆健康发展。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>二十<span lang="EN-US">)</span>强化中医药在&ldquo;两区&rdquo;&ldquo;三平台&rdquo;建设中的作用。推动中医药积极参与中国国际服务贸易交易会、中关村论坛、金融街论坛等重要活动服务保障，推进中医药国际服务。服务国家&ldquo;一带一路&rdquo;建设，支持中医药技术和方案与援外项目有机融合发展，建立中医药国际合作项目库，搭建中医药健康养生国际综合服务平台，实施&ldquo;新时代神农尝百草&rdquo;工程。鼓励国家中医药服务出口基地和中医药服务贸易重点机构开拓国际市场。会同北京冬奥组委做好<span lang="EN-US">2022</span>年北京冬奥会、冬残奥会中医体验服务。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<strong style="mso-bidi-font-weight: normal;">六、加强中医药传承和人才培养</strong></span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>二十一<span lang="EN-US">)</span>建立中医药典籍分类分级传承制度。启动中医医藏保护项目，对医学名家的遗稿、医案、经验方、传统诊疗技术、医疗机构制剂进行挖掘整理，建立中医医学方药录。将医学古籍和传统知识纳入北京中医药数字博物馆建设内容。利用数字化、影像化等技术优化名老中医药工作室活态传承手段，建立传承信息数据库并实现共享。建立名老中医药专家分领域指导教学机制。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>二十二<span lang="EN-US">)</span>加强中医药学术传承向临床服务转化。推动名老中医药专家依托工作室设立以其学术优势和特色为核心的诊所、门诊部，将符合条件的纳入基本医疗保险定点机构。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>二十三<span lang="EN-US">)</span>加强中医药师承教育。制定本市中医师承教育管理办法。支持名老中医药专家开展多层次的师承，培养不同层级的中医药传承人才。建立高年资中医医师带徒激励机制，将师承经历纳入首都名中医评定条件。推进中药企业建立中药专业人员师带徒制度，培养中药行业&ldquo;大国工匠&rdquo;。已开设中医药相关专业的市属高校，要加强中华传统文化知识课程建设，提高中医类专业经典课程比重，开展中医药经典能力等级考试。加大与在京部属高校在中医药传承发展上的合作力度。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>二十四<span lang="EN-US">)</span>分类培养中医药优秀人才。改革中医医师规范化培训制度，建立中医规培师管理制度。允许中西医结合专业人员参加临床类别全科医生规范化培训。启动北京中医院士培育计划，明确&ldquo;北京学者&rdquo;&ldquo;科技新星&rdquo;等北京市重大人才工程对中医药人才的支持。实施基层中医药人才扎根计划、中西医结合人才双优计划、中药技术人才培育计划。开展首都国医名师、首都名中医、首都中青年名中医评定。实施高层次中西医结合人才计划，探索开展优秀中青年西医师学习中医培训班，支持设置中西医结合教学门诊，建立中学西、西学中临床双向互学制度。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>二十五<span lang="EN-US">)</span>改革完善中医药人才职称制度。推行中医药职称分类评审制度，建立基于社会评价、同行评议和以医院绩效考核、师承教育为主体，以中医药服务能力指标为重点的职称分类评价标准。同等条件下评聘高级职称时，可优先评聘长期在基层服务的中医药专业技术人才。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<strong style="mso-bidi-font-weight: normal;">七、促进中医药健康产业发展</strong></span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>二十六<span lang="EN-US">)</span>强化中药材资源管理。建立中药资源普查制度。鼓励龙头中药企业创建国家道地药材良种繁育基地，支持林下中药材种植项目。完善第三方检测机构质量认可制度。鼓励条件适宜的低收入村通过中药材种植增加收入。加强京津冀中药材产业共建共享发展。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>二十七<span lang="EN-US">)</span>加强中药饮片质量监管。修订本市《中药饮片炮制规范》。指导行业协会建立中药饮片分级制度，促进中药饮片优质优价。健全中药饮片质量的协同监管机制，试行医疗机构中药饮片质量责任师岗位制度，完善医疗机构中药饮片质量抽检制度，建立质量信息公告、质量指数和退出管理制度。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>二十八<span lang="EN-US">)</span>加快中药新药研发。实施项目制管理，加强对中药研发机构的指导。增加创新中药和先进中医医疗器械研究开发投入和临床资源支持，完成<span lang="EN-US">3</span>至<span lang="EN-US">5</span>个基于医疗机构制剂的中药新药申报。推进中药临床应用评价工作，定期组织开展本市医疗机构中药临床应用情况的评价，建立与公立医院药品采购、基本药物遴选等的联动机制。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>二十九<span lang="EN-US">)</span>构建中药全过程追溯体系。制定中药大品种目录，完善医疗机构中药使用管理，健全西医合理使用中成药培训制度和处方权授予制度，健全中成药处方前置审核制度和点评制度。促进现代信息技术在中药生产中的应用，推进中药企业诚信体系建设，做好本市信用信息共享平台和公示系统与国家相关系统的对接。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>三十<span lang="EN-US">)</span>实施中医药健康产业精品工程。开发具有中医药健康特点的旅游景点、线路、衍生产品，鼓励发展适宜与旅游产业融合的中医药健康产品和服务项目。健全以中药为原料的食品标准，规范保健食品的宣传和经营行为，开发中医药健康产品，鼓励餐饮企业开发食养服务。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>三十一<span lang="EN-US">)</span>强化中医药健康产业人才支撑。加大对康复、医养结合、养生保健、中药炮制等中医药健康产业技术技能人才教育培养的支持力度。建立中医药健康服务职业技能培训体系。鼓励中医药健康服务机构设立技术技能岗位，健全中医药技能岗位管理制度。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　<strong style="mso-bidi-font-weight: normal;">　八、完善中医药发展保障措施</strong></span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>三十二<span lang="EN-US">)</span>健全中医药管理体制。健全完善市、区两级中医药工作跨部门协调机制，各区党委和政府要建立本区中医药事业组织领导机制，明确承担中医药管理职能的机构。强化首都医药卫生协调委员会推进中医药发展的相关职责，切实依法履行保护、支持、发展中医药事业的责任。市、区要分别将履行中医药发展责任纳入对党委和政府及相关部门的绩效考核。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>三十三<span lang="EN-US">)</span>完善中医药价格和医保政策。建立中医药服务价格动态调整机制。中医医疗服务价格调整时兼顾中医医疗服务体现医务人员技术劳务价值的特点。探索符合中医药特点的医保支付方式，对部分慢性病病种实行按人头付费。对部分中医优势明显、治疗路径清晰、费用明确的病种探索按病种付费，合理确定付费标准。积极将适宜的中医医疗服务项目和中药制剂品种按规定纳入医保范围。</span></p>\n' +
          '<p class="MsoNormal" style="mso-para-margin-top: .5gd; mso-para-margin-right: 0cm; mso-para-margin-bottom: .5gd; mso-para-margin-left: 0cm; line-height: 150%; margin: 7.8pt 0cm 7.8pt 0cm;"><span style="font-size: 12.0pt; line-height: 150%; font-family: \'微软雅黑\',\'sans-serif\';">　　<span lang="EN-US">(</span>三十四<span lang="EN-US">)</span>建立持续稳定的中医药发展多元投入机制。在切实保障公立中医医院政府投入责任落实的基础上，对其提供的中药饮片、中药制剂、中医非药物疗法等特色服务继续执行中医药特色绩效考核补偿。吸引社会资本投资中医药健康产业，引导商业保险机构、社会基金支持中医药产业发展。</span></p>\n '
    }
  }
}
</script>

<style scoped>

</style>
